"""
ScriptPulse Print Summary Generator
Creates a concise 1-page summary for writers to print and pin.
"""

def generate_print_summary(report_data, script_title="Untitled Script"):
    """
    Generate a clean, printable 1-page HTML summary.
    """
    
    # Extract key metrics
    trace = report_data.get('temporal_trace', [])
    avg_tension = sum(p['attentional_signal'] for p in trace) / len(trace) if trace else 0
    
    valence_scores = report_data.get('valence_scores', [])
    avg_valence = sum(valence_scores) / len(valence_scores) if valence_scores else 0
    
    runtime = report_data.get('runtime_estimate', {}).get('avg_minutes', 0)
    
    # Get top problems
    scene_feedback = report_data.get('scene_feedback', {})
    all_warnings = []
    for scene_idx, notes in scene_feedback.items():
        warning_notes = [n for n in notes if n['severity'] == 'warning']
        for note in warning_notes[:2]:  # Top 2 per scene
            all_warnings.append({
                'scene': scene_idx + 1,
                'issue': note['issue'],
                'fix': note['suggestion']
            })
    
    top_problems = all_warnings[:5]  # Top 5 overall
    
    # Get strengths (scenes with high tension + positive valence)
    strengths = []
    for i, point in enumerate(trace):
        if point['attentional_signal'] > 0.7 and valence_scores[i] > 0.1:
            strengths.append(f"Scene {i+1}: High energy, positive tone")
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            h1 {{ font-size: 18px; border-bottom: 2px solid #333; }}
            h2 {{ font-size: 14px; margin-top: 15px; }}
            .metric {{ display: inline-block; margin-right: 30px; }}
            .problem {{ background: #ffe6e6; padding: 5px; margin: 5px 0; }}
            .strength {{ background: #e6ffe6; padding: 5px; margin: 5px 0; }}
        </style>
    </head>
    <body>
        <h1>{script_title} - Quick Summary</h1>
        
        <div class="metric">📊 Intensity: {int(avg_tension * 10)}/10</div>
        <div class="metric">🎭 Tone: {"Happy" if avg_valence > 0.1 else "Serious" if avg_valence < -0.1 else "Balanced"}</div>
        <div class="metric">⏱️ Length: ~{runtime} min</div>
        
        <h2>🔴 Top Problems to Fix</h2>
        {''.join([f'<div class="problem"><b>Scene {p["scene"]}</b>: {p["issue"]} → {p["fix"]}</div>' for p in top_problems]) if top_problems else '<p>No major issues detected!</p>'}
        
        <h2>✅ Top Strengths</h2>
        {''.join([f'<div class="strength">• {s}</div>' for s in strengths[:5]]) if strengths else '<p>Build more high-energy scenes.</p>'}
        
        <p style="margin-top: 20px; font-size: 10px; color: #666;">Generated by ScriptPulse v14.0</p>
    </body>
    </html>
    """
    
    return html
